print(get_color_from_image_pixel(r"C:\Users\SpaceCoder\OneDrive\Desktop\Py files\test.png",1,0,'rgba'))
print(get_color_from_image_pixel(r"C:\Users\SpaceCoder\OneDrive\Desktop\Py files\test.png",1,0,'rgb'))
print(get_color_from_image_pixel(r"C:\Users\SpaceCoder\OneDrive\Desktop\Py files\test.png",1,0,'hexa'))
print(get_color_from_image_pixel(r"C:\Users\SpaceCoder\OneDrive\Desktop\Py files\test.png",1,0,'hex'))
print(get_color_from_image_pixel(r"C:\Users\SpaceCoder\OneDrive\Desktop\Py files\test.png",1,0,'hsl'))
print(get_color_from_image_pixel(r"C:\Users\SpaceCoder\OneDrive\Desktop\Py files\test.png",1,0,'hsla'))
